//
//  LinkedListCycleTest.swift
//  SwiftChallengesTests
//
//  Generated by KyleLearnedThis on 4/26/26.
//

import XCTest

class LinkedListCycleTest: XCTestCase {
    let solution = LinkedListCycle()

    func testNilHead() {
        XCTAssertFalse(solution.hasCycle(nil))
    }

    func testSingleNodeNoCycle() {
        let node = ListNode(1)
        XCTAssertFalse(solution.hasCycle(node))
    }

    func testLinearListNoCycle() {
        let n1 = ListNode(1)
        let n2 = ListNode(2)
        let n3 = ListNode(3)
        n1.next = n2
        n2.next = n3
        XCTAssertFalse(solution.hasCycle(n1))
    }

    func testCycleAtTail() {
        let n1 = ListNode(1)
        let n2 = ListNode(2)
        let n3 = ListNode(3)
        n1.next = n2
        n2.next = n3
        n3.next = n1
        XCTAssertTrue(solution.hasCycle(n1))
    }

    func testCycleInMiddle() {
        let n1 = ListNode(1)
        let n2 = ListNode(2)
        let n3 = ListNode(3)
        let n4 = ListNode(4)
        n1.next = n2
        n2.next = n3
        n3.next = n4
        n4.next = n2
        XCTAssertTrue(solution.hasCycle(n1))
    }

    func testTwoNodeCycle() {
        let n1 = ListNode(1)
        let n2 = ListNode(2)
        n1.next = n2
        n2.next = n1
        XCTAssertTrue(solution.hasCycle(n1))
    }
}
